project:
  type: website
  output-dir: docs

website:
  title: "Predicción Estacional · AEMET–Tragsatec"
  description: "Resultados del servicio de predicción estacional"
  site-url: https://sanfiz.github.io/aemet-tragsatec-2026/
  favicon: images/logos/aemet.png
  navbar: false
  page-footer:
    left: "© 2026 · Generado por los autores con HTML & CSS"
    center: "Marta Domínguez · Martín Senande · Sabela Sanfiz (Tragsatec) · Esteban Rodríguez (AEMET)"
    right: "Tragsatec · AEMET · Predicción Estacional · 2024–2026"
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: full
    include-before-body: hamburger.html

resources:
  - images/